server:
  persistentVolume:
    enabled: true
    existingClaim: prometheus-pvc
    storageClass: ""
    size: 5Gi

alertmanager:
  persistentVolume:
    enabled: false

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'teamcity'
        static_configs:
          - targets: ['host.minikube.internal:8111']

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['prometheus-kube-state-metrics.monitoring.svc.cluster.local:8080']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['prometheus-prometheus-node-exporter.monitoring.svc.cluster.local:9100']
